[[language]]
name = "rust"

[language-server.rust-analyzer.config]
cargo = { features = ["urdf", "macro"] }
rustfmt.rangeFormatting.enable = true
rustfmt.extraArgs = ["+nightly"]
files.excludeDirs = ["kinema/examples"]
